FROM python:3.8-slim

ENV PYTHONBUFFERED True

ENV APP_HOME / app

WORKDIR $APP_HOME

COPY . ./

RUN pip install Flask gunicorn

CMD excec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 __init__:app